# Generated by Django 3.2.9 on 2022-01-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('participants', models.CharField(default='', max_length=200)),
                ('date', models.CharField(default='', max_length=200)),
                ('place', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=2000)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
