# Generated by Django 4.0.1 on 2022-01-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Disp',
        ),
    ]
