# Generated by Django 3.2.9 on 2022-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20220111_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='merop',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='merop',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='merop',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='merop',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='merop',
            name='participants',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='merop',
            name='place',
            field=models.CharField(default='', max_length=200),
        ),
    ]
